DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS books;

CREATE TABLE IF NOT EXISTS books(
    id IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    pub_year INT NOT NULL
);

CREATE TABLE IF NOT EXISTS comments(
    id IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL,
    author VARCHAR(64) NOT NULL,
    text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);